export const SET_CURRENT_ROLE = "SET_CURRENT_ROLE";
export const SET_AVAILABLE_ROLES = "SET_AVAILABLE_ROLES";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ETAG = "SET_ETAG";

export const SET_OPEN_CONFIRM = 'SET_OPEN_CONFIRM';
export const SET_OPEN_ALERT = 'SET_OPEN_ALERT';

export const UPDATE_REGISTRATION_DATA = "UPDATE_REGISTRATION_DATA";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_BILLING_DETAILS = "UPDATE_BILLING_DETAILS";
export const UPDATE_PERSONAL_DATA = "UPDATE_PERSONAL_DATA";
export const SET_FIRST_PAGE_REGISTRATION_STATUS =
  "SET_FIRST_PAGE_REGISTRATION_STATUS";
export const SET_SECOND_PAGE_REGISTRATION_STATUS =
  "SET_SECOND_PAGE_REGISTRATION_STATUS";
export const SET_THIRD_PAGE_REGISTRATION_STATUS =
  "SET_THIRD_PAGE_REGISTRATION_STATUS";

export const SET_SERVICE_PARAMETER_VALUE = "SET_SERVICE_PARAMETER_VALUE";
export const SET_CLIENT_FOR_ORDER = "SET_CLIENT_FOR_ORDER";
export const SET_DEVICES_FOR_ORDER = "SET_DEVICES_FOR_ORDER";
export const SEND_ORDER_TO_SETTLEMENT = 'SEND_ORDER_TO_SETTLEMENT';
export const CLOSE_ORDER = 'CLOSE_ORDER';
export const SET_ORDER_IN_EDITION = 'SET_ORDER_IN_EDITION';

export const SET_REPORT_PERIOD_YEAR = "SET_REPORT_PERIOD_YEAR";
export const SET_REPORT_PERIOD_MONTH = "SET_REPORT_PERIOD_MONTH";
