version:  "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todo" ]
      interval: 30s
      timeout: 10s
      retries: 5
